task: "nn"

qd:
    n: 10
    p: 0.1
    rep: "turtle"
    game: "smb"

mcts:
    game: "connect_four"
    maxim: "human"
    minim: "alpha_beta"
    maxDepth: 6
    # compute: 10
    # c: 0.9

nn:
    hidden: 30
    epochs: 50
    learning_rate: 0.01
