task: "qd"

qd:
    n: 10
    p: 0.1
    sigma: 0.01
    generation: 10 # how many generations do we run?
    proportion: 0.2 # top we keep?
    dimensions: 2000
    population: 100
    rep: "turtle"
    game: "smb"

mcts:
    game: "connect_four"
    maxim: "human"
    minim: "monte_carlo"
    maxDepth: 6
    compute: 10
    c: 0.9

nn:
    hidden: 30
    epochs: 50
    lr: 0.0001
