task: "mcts"

qd:
    n: 10
    p: 0.1
    rep: "turtle"
    game: "smb"

mcts:
    game: "connect_four"
    maxim: "human"
    minim: "monte_carlo"
    maxDepth: 6
    compute: 10
    c: 0.9

nn:
    hidden: 30
    epochs: 50
    lr: 0.0001
